### PR TITLE
Updates for Swift 5

### PR DESCRIPTION
**Pull request by nickoneill**
Ran `pod install` again and it made some pbx changes too

### CODE REVIEW

**Comment by nickoneill** [comment]
The latest `Down` version has a default styler that gets rid of that weird CSS lag when loading issues. Plus we get to use some swiftpm

**Comment by nickoneill** [comment]
what am I doing wrong here? Swiftpm packages are just broken on CircleCI AND bitrise? Can't be.

**Comment by nickoneill** [comment]
This *should* be fixed in 2.138: https://github.com/fastlane/fastlane/issues/15454

**Comment by nickoneill** [comment]
OK, no more SPM integration, if it wasn't builds failing it was tests. This PR only upgrades to Swift 5 and bumps the versions on R.Swift and Down to get the new, faster styler behavior.

**Comment by mccarron** [comment]
I want to use SPM but still seems not quite ready. :/ 

:shipit:

**Comment by subdigital** [comment]
Maybe next year! 😅

**Comment by kamitchell** [comment]
> This should be fixed in 2.138

@nickoneill I saw your mention on a Fastlane issue that I'm tracking. Not everything for SwiftPM is in Fastlane, in particular there's an open PR fastlane/fastline#15505 that has more fixes.

I found this out after our project was past the point of no return having thrown in with SPM, so I just put this in our `Gemfile`:

```
gem 'fastlane', :git => 'https://github.com/bguidolim/fastlane', :branch => 'fix-swiftpm-resolve'
```

It seemed the path of least resistance to getting the app out. So that's there if you decided to revisit SPM in the future.

**Comment by nickoneill** [comment]
Thanks @kamitchell! It was easy enough to revert back to pre-swiftpm for the one dep we moved over, but I appreciate the heads up. I'll keep an eye on https://github.com/fastlane/fastlane/pull/15505 for future reference

**Comment by bguidolim** [comment]
@kamitchell @nickoneill btw, it was just merged.

**Comment by nickoneill** [comment]
Thanks @bguidolim

**Pull request merged**
