### PR TITLE
New graphical elements in call script

### PR DESCRIPTION
**Pull request by bengottlieb**

### CODE REVIEW

**Comment by mccarron** [comment]
Nice idea. Can you attach a screenshot to what it looks like really quick?

**Comment by bengottlieb** [comment]
screen shot 2017-03-08 at 4 47 51 pm

**Comment by mccarron** [comment]
Oh I like that. Maybe move the arrow after the "Busy?" 

What are your thoughts @subdigital?

**Comment by subdigital** [comment]
Yeah, I think @mccarron is right. Otherwise LGTM.

**Comment by bengottlieb** [comment]
Flipped.
screen shot 2017-03-10 at 7 06 48 pm

**Comment by subdigital** [comment]
I got some feedback to change this dropdown to an action sheet, which makes a lot of sense. Do you want to tackle this as part of this PR?

**Comment by bengottlieb** [comment]
Sure ting

**Comment by mccarron** [comment]
Thanks for that change @bengottlieb. 👍

**Pull request merged**
