### PR TITLE
Dynamic Type support - About Screen & Onboarding Screens

### PR DESCRIPTION
**Pull request by iainsmith**
This PR adds basic Dynamic Type support (#144) to the AboutViewController & two page Onboarding Screens. First pass only to support xSmall - xxxLarge.

## Change in the PR

| Screen | Small | xxxLarge |
| --- | --- | --- |
|About | screen shot 2018-10-10 at 21 28 07 | screen shot 2018-10-10 at 21 28 24 |
| Onboarding 1 | screen shot 2018-10-10 at 21 28 37 | screen shot 2018-10-10 at 21 28 56 |
| Onboarding 2 | screen shot 2018-10-10 at 21 28 41 | screen shot 2018-10-10 at 21 28 59 |

## Deferred to later

* Onboarding - Text can not be scrolled at AX1 - AX5
* About - Text disappears if you change the Dynamic type size while the AboutViewController is on screen.

### CODE REVIEW

**Comment by nickoneill** [comment]
Ready to review for this @iainsmith?

**Comment by iainsmith** [comment]
Yes, this one is good to go.

**Comment by Abizern** [comment]
Amazing what can be done with just Storyboards 👍

**Comment by iainsmith** [comment]
Hey @nickoneil, is there anything you’d like me to add for this PR?

**Pull request merged**
