### PR TITLE
add code coverage to fastlane

### PR DESCRIPTION
**Pull request by cselin**
Adds code coverage lane which can be used to ensure minimum coverage
Screenshot 2024-01-11 at 9 58 21 AM

### CODE REVIEW

**Comment by cselin** [comment]
@nickoneill this was easier than I thought using the (old) xcov tool with fastlane. I've verified this works locally and errors if minimum coverage goes below 24.0%. The only missing piece is how to integrate this with Bitrise which I don't seem to be able to tap into for this app even on a fork, it goes to your workspace.

**Comment by cselin** [comment]
Seems like we can probably remove `scan` from `coverage` lane and just update `fastlane "ios" "test"` -> `fastlane "ios" "test" "coverage"`

**Comment by nickoneill** [comment]
changed the bitrise invocation, let's see if it does the right thing for this branch

**Review by nickoneill — APPROVED** [review]
needs two steps, `ios test` and `ios coverage` but it works great

**Pull request merged**
