### PR TITLE
Dynamic type support - Issue Detail & Call Script

### PR DESCRIPTION
**Pull request by iainsmith**
**Updated 10 Oct 18**

This PR adds basic Dynamic Type support (#144) to the IssueDetailViewController & CallScriptViewController.

## Approach

The changes for full Dynamic Type support are going to land up touching each screen so I'd suggest we break this into multiple PR's if that sounds good with everyone? There are a lot of Gotchas when trying to support the Extra large AX1 - AX5 sizes so I'd suggest we break this down as follows:

* Pull Request into master for 1-2 screens at a time
* First iteration -> Best effort to support xSmall -> xxxLarge with minimal refactoring. (Largely storyboard changes)
* Future iterations -> Improvements to AX1-AX5 font sizes or that require larger code changes (Moving to StackViews, etc)
* I'd like to suggest we ignore visual defects that:
    * are only reproducible when changing Dynamic Type while a ViewController is on screen. This is such a low usage scenario that it’s not worth focusing on imho. 
    * only occur at the extra large sizes AX1-AX5 for the first few passes.

Does that sound like a reasonable approach to everyone?

## Changes in the PR

|Screen | small | xxxLarge |
| --- | --- | --- |
| Issue Detail | detail-small | detail-xxxlarge |
| Issue Detail + profile | detail-profile-small | detail-profile-xxxlarge |
| Call Page | call-small | call-large |

## Deferred to later

* The Call Script page uses a collectionView for the dynamic buttons. To support dynamic height here we'd either have to look at resizable CollectionViewCells or potentially move to a simpler Stack View layout that can easily switch between a grid and a vertical stack.
* The Call Script header breaks down at AX2

### CODE REVIEW

**Comment by Abizern** [comment]
As it's a WIP branch it's maybe not mergeable yet, but looks good so far, I think

**Comment by mccarron** [comment]
Looks like a good starting point, keep it up. Definitely try to expand labels where you can, but curious what we should do about the buttons. 🤔

**Comment by mccarron** [comment]
Thanks for updating the screens, I think it looks great, lets merge it in.

**Comment by nickoneill** [comment]
Thanks @iainsmith! This looks great, I really appreciate the visual examples

**Pull request merged**
