### PR TITLE
Remove the copy warning

### LINKED ISSUE #301: iPad crash in iOS 13
Looks like these are all on iPad

> IssueScriptCell.swift, line 14
SIGABRT: Your application has presented a UIAlertController (<UIAlertController: 0x10613b400>) of style UIAlertControllerStyleActionSheet from UINavigationController (<UINavigationController: 0x1060b7e00>). The modalPresentationStyle of a UIAlertController with this style is UIModalPresentationPopover. You must provide location information for this popover through the alert controller's popoverPresentationController. You must provide either a sourceView and sourceRect or a barButtonItem. If this information is not known when you present the alert controller, you may provide it in the UIPopoverPresentationControllerDelegate method -prepareForPopoverPresentation.

### PR DESCRIPTION
**Pull request by nickoneill**
Fixes #301 

It causes a crash in certain cases on iPads and imho is not effective.

### CODE REVIEW

**Comment by Abizern** [comment]
I was taking a look at this when I saw the PR. If the warning is out the resources and user defaults key might as well be out as well.

**Comment by nickoneill** [comment]
Thanks! Definitely good to clean up these items if they're not being used. Will merge shortly

**Comment by Abizern** [comment]
Just FYI - the Bitrise checks completed successfully, there's just a problem sending the results back to GitHub.

**Comment by nickoneill** [comment]
Weird, looks good though!

**Pull request merged**
