### PR TITLE
Update LocationSheet.swift

### PR DESCRIPTION
**Pull request by yinuoyang01**
Fix accessibility issues of the magnifying glass search button

### CODE REVIEW

**Comment by nickoneill** [comment]
Thank you! Can you add these strings into the localization files and use the generated `R.localization` strings in the code?

**Comment by yinuoyang01** [comment]
> Thank you! Can you add these strings into the localization files and use the generated `R.localization` strings in the code?

Hi, do you mean add the new strings to the corresponding language files to support more languages?

**Comment by yinuoyang01** [comment]
Hi, I have change the text to use the generated R.localization strings.

**Comment by nickoneill** [comment]
We don't need translations for other languages, but we store all our strings in `Localizable.strings` so that if we want to localize in the future, we can simply translate that file to start the process.

Currently you set the accessibility label to `R.string.localizable.detectLocation()` which is `detect-location` in `Localizable.strings`, so it would read "Detect my location" which is incorrect for that button. I think your original label is correct "Search Location", you just need to add a new line in `Localizable.strings` for this (match the styles already in that file for the name) and then replace the usage with `R.string.localizable.whateverYouCalledYourString()`

**Comment by yinuoyang01** [comment]
Got it, I have added the string to Localizable.strings and replace the usage.

**Review by nickoneill — APPROVED** [review]

**Comment by nickoneill** [comment]
Thanks! We'll get this into the next release

**Comment by nickoneill** [comment]
Sorry, one more thing: you need a semicolon at the end of the line in the strings file @yinuoyang01

**Comment by yinuoyang01** [comment]
> Sorry, one more thing: you need a semicolon at the end of the line in the strings file @yinuoyang01

Hi, sorry to miss that, I have added the semicolon!

**Comment by nickoneill** [comment]
Thanks!

**Pull request merged**
