### PR TITLE
Dark mode for Scheduling reminders

### PR DESCRIPTION
**Pull request by Abizern**
Dark mode for enabling reminders.

Partly addresses #278

I think that's it for the initial pass over the About.Storyboard.

Haven't made changes to the Open Source acknowledgements as the controllers for that come from a Pod and I don't want to go into that.

Sorry about the small PRs. I keep thinking I'm done for the day and then do a little bit more.

### CODE REVIEW

**Comment by Abizern** [comment]
I'm making lots of small changes, Moving colors to the Asset catalog and using them in the storyboards. Once it's all done then a more detailed UI pass can be made and the colors in the catalog can be tweaked to look their best on light or dark mode.

**Comment by Abizern** [comment]
Reminder-None-Light
Reminder-Chosen-Light
Reminder-Empty-Light

**Comment by Abizern** [comment]
Reminder-Chosen-Dark
Reminder-Empty-Dark
Reminder-None-Dark

**Comment by nickoneill** [comment]
Sorry for the wait on this, will review this weekend

**Comment by nickoneill** [comment]
Appreciate the work moving these to the color catalog. I'm going to take a stab at mocking something that has better readability than blue-on-dark-grey but we can continue making these improvements on the color handling in parallel.

**Comment by Abizern** [comment]
I've been a bit lazy with naming the colours. Semantic labelling would be better and maybe even provide cognitive freedom to use different colours entirely.

**Pull request merged**
